# Generated by Django 4.2.16 on 2026-07-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DutyDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField()),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('leg1_miles', models.FloatField(default=0)),
                ('leg1_hours', models.FloatField(default=0)),
                ('leg2_miles', models.FloatField(default=0)),
                ('leg2_hours', models.FloatField(default=0)),
                ('total_miles', models.FloatField(default=0)),
                ('total_drive_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('total_duration_hours', models.FloatField(default=0)),
                ('total_days', models.IntegerField(default=0)),
                ('route_geometry', models.JSONField(blank=True, default=list)),
                ('routing_provider', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('rest', 'Rest'), ('restart', 'Restart'), ('break', 'Break')], max_length=16)),
                ('label', models.CharField(max_length=255)),
                ('mile_marker', models.FloatField()),
                ('start_hour', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['start_hour'],
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_hour', models.FloatField()),
                ('end_hour', models.FloatField()),
                ('status', models.CharField(choices=[('OFF_DUTY', 'Off Duty'), ('SLEEPER_BERTH', 'Sleeper Berth'), ('DRIVING', 'Driving'), ('ON_DUTY_NOT_DRIVING', 'On Duty Not Driving')], max_length=32)),
                ('location_label', models.CharField(blank=True, default='', max_length=255)),
                ('duty_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.dutyday')),
            ],
            options={
                'ordering': ['start_hour'],
            },
        ),
        migrations.AddField(
            model_name='dutyday',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='dutyday',
            unique_together={('trip', 'day_number')},
        ),
    ]
